repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    # -   id: trailing-whitespace
    # -   id: end-of-file-fixer
    # -   id: check-yaml
    # -   id: check-added-large-files
-   repo: https://github.com/python-poetry/poetry
    rev: 1.1.4
    hooks:
    -   id: poetry-lock
    -   id: poetry-export
        args: ["--without-hashes", "--without-dev", "-f", "requirements.txt", "-o", "requirements.txt"]
    -   id: poetry-install
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format