"""init migration

Revision ID: 46155d043b4c
Revises:
Create Date: 2024-09-28 06:27:18.196309

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46155d043b4c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    achievements_table = op.create_table(
        "achievements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("verb", sa.String(length=100), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    attendance_types_table = op.create_table(
        "attendance_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    event_categories_table = op.create_table(
        "event_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    event_tags_table = op.create_table(
        "event_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("color", sa.String(length=30), nullable=True),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    org_types_table = op.create_table(
        "org_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    permissions_table = op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    roles_table = op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "slack_spaces",
        sa.Column("team_id", sa.String(length=100), nullable=False),
        sa.Column("workspace_name", sa.String(length=100), nullable=True),
        sa.Column("bot_token", sa.String(length=100), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.PrimaryKeyConstraint("team_id"),
    )
    event_types_table = op.create_table(
        "event_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("acronym", sa.String(length=30), nullable=True),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["event_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orgs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("org_type_id", sa.Integer(), nullable=False),
        sa.Column("default_location_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("logo", sa.LargeBinary(), nullable=True),
        sa.Column("website", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("twitter", sa.String(length=100), nullable=True),
        sa.Column("facebook", sa.String(length=100), nullable=True),
        sa.Column("instagram", sa.String(length=100), nullable=True),
        sa.Column("slack_id", sa.String(length=30), nullable=True),
        sa.Column("last_annual_review", sa.Date(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_type_id"],
            ["org_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["orgs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    roles_x_permissions_table = op.create_table(
        "roles_x_permissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "achievements_x_orgs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("achievement_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_tags_x_org",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_tag_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("color_override", sa.String(length=30), nullable=True),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_tag_id"],
            ["event_tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_types_x_org",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_type_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["event_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("address_street", sa.String(length=255), nullable=True),
        sa.Column("address_city", sa.String(length=100), nullable=True),
        sa.Column("address_state", sa.String(length=45), nullable=True),
        sa.Column("address_zip", sa.String(length=45), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orgs_x_slack_spaces",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("slack_space_team_id", sa.String(length=100), nullable=False),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slack_space_team_id"],
            ["slack_spaces.team_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("f3_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("home_region_id", sa.Integer(), nullable=True),
        sa.Column("avatar_url", sa.String(length=255), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.ForeignKeyConstraint(
            ["home_region_id"],
            ["orgs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "achievements_x_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("achievement_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date_awarded", sa.Date(), nullable=False),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("event_type_id", sa.Integer(), nullable=True),
        sa.Column("event_tag_id", sa.Integer(), nullable=True),
        sa.Column("series_id", sa.Integer(), nullable=True),
        sa.Column("is_series", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("highlight", sa.Boolean(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("start_time", postgresql.TIME(), nullable=True),
        sa.Column("end_time", postgresql.TIME(), nullable=True),
        sa.Column("day_of_week", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("recurrence_pattern", sa.String(length=30), nullable=True),
        sa.Column("recurrence_interval", sa.Integer(), nullable=True),
        sa.Column("index_within_interval", sa.Integer(), nullable=True),
        sa.Column("pax_count", sa.Integer(), nullable=True),
        sa.Column("fng_count", sa.Integer(), nullable=True),
        sa.Column("preblast", sa.TEXT(), nullable=True),
        sa.Column("backblast", sa.TEXT(), nullable=True),
        sa.Column("preblast_rich", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("backblast_rich", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("preblast_ts", sa.Double(precision=16, decimal_return_scale=6), nullable=True),
        sa.Column("backblast_ts", sa.Double(precision=16, decimal_return_scale=6), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_tag_id"],
            ["event_tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["event_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles_x_users_x_orgs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "user_id", "org_id", name="_role_user_org_uc"),
    )
    op.create_table(
        "slack_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slack_id", sa.String(length=100), nullable=False),
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("avatar_url", sa.String(length=255), nullable=True),
        sa.Column("slack_team_id", sa.String(length=100), nullable=False),
        sa.Column("strava_access_token", sa.String(length=100), nullable=True),
        sa.Column("strava_refresh_token", sa.String(length=100), nullable=True),
        sa.Column("strava_expires_at", sa.DateTime(), nullable=True),
        sa.Column("strava_athlete_id", sa.Integer(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("slack_updated", sa.DateTime(), nullable=True),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attendance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("attendance_type_id", sa.Integer(), nullable=False),
        sa.Column("is_planned", sa.Boolean(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.Column("updated", sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False),
        sa.ForeignKeyConstraint(
            ["attendance_type_id"],
            ["attendance_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "user_id", "attendance_type_id", "is_planned", name="event_user"),
    )
    # initializing some of the tables
    op.bulk_insert(
        table=org_types_table,
        rows=[
            {"name": "AO"},
            {"name": "Region"},
            {"name": "Area"},
            {"name": "Sector"},
        ],
    )
    op.bulk_insert(
        table=achievements_table,
        rows=[
            {
                "name": "The Priest",
                "description": "Post for 25 QSource lessons",
                "verb": "posting for 25 QSource lessons",
            },
            {
                "name": "The Monk",
                "description": "Post at 4 QSources in a month",
                "verb": "posting at 4 QSources in a month",
            },
            {
                "name": "Leader of Men",
                "description": "Q at 4 beatdowns in a month",
                "verb": "Qing at 4 beatdowns in a month",
            },
        ],
    )
    op.bulk_insert(
        table=event_categories_table,
        rows=[
            {"name": "1st F - Core Workout", "description": "The core F3 activity - must meet all 5 core principles."},
            {"name": "1st F - Pre Workout", "description": "Pre-workout activities (pre-rucks, pre-runs, etc)."},
            {
                "name": "1st F - Off the books",
                "description": "Fitness activities that didn't meet all 5 core principles (unscheduled, open to all men, etc).",  # noqa: E501
            },
            {"name": "2nd F - Fellowship", "description": "General category for 2nd F events."},
            {"name": "3rd F - Faith", "description": "General category for 3rd F events."},
        ],
    )
    op.bulk_insert(
        table=event_types_table,
        rows=[
            {"name": "Bootcamp", "category_id": 1, "acronym": "BC"},
            {"name": "Run", "category_id": 1, "acronym": "RU"},
            {"name": "Ruck", "category_id": 1, "acronym": "RK"},
            {"name": "QSource", "category_id": 3, "acronym": "QS"},
        ],
    )
    op.bulk_insert(
        table=attendance_types_table,
        rows=[
            {"type": "PAX"},
            {"type": "Q"},
            {"type": "Co-Q"},
        ],
    )
    op.bulk_insert(
        table=event_tags_table,
        rows=[
            {"name": "Open", "color": "Green"},
            {"name": "VQ", "color": "Blue"},
            {"name": "Manniversary", "color": "Yellow"},
            {"name": "Convergence", "color": "Orange"},
        ],
    )
    op.bulk_insert(
        table=permissions_table,
        rows=[
            {"name": "All"},
        ],
    )
    op.bulk_insert(
        table=roles_table,
        rows=[
            {"name": "Admin"},
        ],
    )
    op.bulk_insert(
        table=roles_x_permissions_table,
        rows=[
            {"role_id": 1, "permission_id": 1},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attendance")
    op.drop_table("slack_users")
    op.drop_table("roles_x_users_x_orgs")
    op.drop_table("events")
    op.drop_table("achievements_x_users")
    op.drop_table("users")
    op.drop_table("orgs_x_slack_spaces")
    op.drop_table("locations")
    op.drop_table("event_types_x_org")
    op.drop_table("event_tags_x_org")
    op.drop_table("achievements_x_orgs")
    op.drop_table("roles_x_permissions")
    op.drop_table("orgs")
    op.drop_table("event_types")
    op.drop_table("slack_spaces")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_table("org_types")
    op.drop_table("event_tags")
    op.drop_table("event_categories")
    op.drop_table("attendance_types")
    op.drop_table("achievements")
    # ### end Alembic commands ###
