from __future__ import annotations

from typing import Protocol

from application.series import SeriesData


class SeriesRepository(Protocol):
    def get_by_region(self, region_id: int, ao_id: int | None = None) -> list[SeriesData]:
        """Return active series for a region, optionally filtered to a single AO."""
        ...

    def get_by_id(self, series_id: int) -> SeriesData | None:
        """Return a single series, or *None* if not found."""
        ...

    def create(
        self,
        region_id: int,
        ao_id: int,
        name: str,
        start_date: str,
        start_time: str | None,
        end_time: str | None,
        day_of_week: str,
        description: str | None,
        location_id: int | None,
        end_date: str | None,
        recurrence_pattern: str | None,
        recurrence_interval: int | None,
        index_within_interval: int | None,
        event_type_ids: list[int],
        event_tag_ids: list[int],
        is_active: bool,
        is_private: bool,
        highlight: bool,
        meta: dict | None,
    ) -> SeriesData:
        """Create a new series.  Future instances are generated by the API cascade."""
        ...

    def update(
        self,
        series_id: int,
        region_id: int,
        ao_id: int,
        name: str,
        start_date: str,
        start_time: str | None,
        end_time: str | None,
        description: str | None,
        location_id: int | None,
        end_date: str | None,
        event_type_ids: list[int],
        event_tag_ids: list[int],
        is_active: bool,
        is_private: bool,
        highlight: bool,
        meta: dict | None,
    ) -> SeriesData:
        """Update an existing series.  Future instances are updated by the API cascade."""
        ...

    def delete(self, series_id: int) -> None:
        """Soft-delete a series.  Future instances are deleted by the API cascade."""
        ...
