steps:
  - name: gcr.io/cloud-builders/gcloud
    id: prepare-context
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        rm -rf scripts_build_ctx
        mkdir -p scripts_build_ctx
        # Copy scripts package
        cp -a scripts scripts_build_ctx/
        # Copy shared code needed by scripts (add/remove as needed)
        [ -d features ] && cp -a features scripts_build_ctx/ || true
        [ -d utilities ] && cp -a utilities scripts_build_ctx/ || true
        [ -d common ] && cp -a common scripts_build_ctx/ || true
        # Clean Python caches
        find scripts_build_ctx -type d -name __pycache__ -prune -exec rm -rf {} +
        find scripts_build_ctx -type f -name '*.pyc' -delete

  - name: gcr.io/cloud-builders/docker
    id: build-image
    args:
      - build
      - -t
      - $_IMAGE
      - -f
      - scripts/Dockerfile
      - scripts_build_ctx

images:
  - $_IMAGE
substitutions:
  _IMAGE: us-central1-docker.pkg.dev/PROJECT/REPO/f3-bot-scripts:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY